package views;

import controllers.BairroController;
import models.Bairro;
import tools.CaixaDeDialogo;
import tools.Combos;
import tools.Validacao;
//import tools.Formatacao;

public class CadBairros extends javax.swing.JFrame {

    Bairro objBairro;
    BairroController objBairroControle;
    Combos cbCombos;

    public CadBairros() {
        initComponents();

        try {
            cbCombos = new Combos(jcbCidade);
            cbCombos.preencheCombo("SELECT id, nome, uf FROM cidades ORDER BY nome");
        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem(ex.getMessage());
        }
        limparTela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblNomeBairro = new javax.swing.JLabel();
        txtNomeBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        jcbCidade = new javax.swing.JComboBox<>();
        btnSalvarBairro = new javax.swing.JButton();
        btnLimparBairro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbBairros = new javax.swing.JTable();
        lblAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro de Bairros");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 177, -1));

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblId.setText("ID");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lblNomeBairro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNomeBairro.setText("Nome do Bairro *");
        getContentPane().add(lblNomeBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 66, -1, -1));
        getContentPane().add(txtNomeBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 88, 180, -1));

        lblCidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCidade.setText("Cidade *");
        getContentPane().add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 128, -1, -1));

        jcbCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 150, 150, -1));

        btnSalvarBairro.setText("SALVAR");
        btnSalvarBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarBairroActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 191, -1, -1));

        btnLimparBairro.setText("LIMPAR");
        btnLimparBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparBairroActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimparBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 191, -1, -1));

        jtbBairros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbBairros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbBairrosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbBairros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 225, 376, 163));

        lblAviso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAviso.setText("Campos com * são obrigatórios");
        getContentPane().add(lblAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 394, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbBairrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbBairrosMousePressed
        try {

            //pega a linha selecionada
            int linhaSelecionada = jtbBairros.getSelectedRow();

            // Primeira coluna da linha
            String codigo = jtbBairros.getModel().getValueAt(linhaSelecionada, 0).toString();

            //Verifica se clicou na coluna 2 => EXCLUIR
            if (jtbBairros.isColumnSelected(2)) {
                try {
                    boolean wPergunta = CaixaDeDialogo.obterinstancia()
                            .pedirConfirmacao("Tem certeza de que deseja excluir?", "", 'p');
                    if (wPergunta == true) {
                        //exclusão do registro selecionado
                    }

                    atualizarTabela();

                } catch (Exception ex) {
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
                }
            } else {
                //buscar no banco de dados o registro e preencher nos campos da tela
                BairroController candController = new BairroController();
                Bairro objeto = candController.buscarBairro(codigo);
                if (objeto != null) {
                    preencherCampos(objeto);
                }
            }

        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem(ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_jtbBairrosMousePressed

    private void btnSalvarBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarBairroActionPerformed
        try {
            boolean retorno;
            //validar os campos
            retorno = validarDados();
            if (retorno) {

                objBairro = new Bairro();
                objBairro.setNome(txtNomeBairro.getText());

                Combos objCombo = (Combos) jcbCidade.getSelectedItem();
                String id_cidade = objCombo.getCodigo();
                objBairro.setId_cidade(Integer.parseInt(id_cidade));

                BairroController objBaiController = new BairroController();
                if (lblId.getText().equals("ID")) {
                    retorno = objBaiController.incluirBairro(objBairro);
                } else {
                    objBairro.setId(Integer.parseInt(lblId.getText()));
                    retorno = objBaiController.alterarBairro(objBairro);
                }

                if (retorno == false) {
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao alterar/incluir", "Erro", "e");
                } else {
                    limparTela();
                }

            }

            atualizarTabela();

        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao tentar incluir");
            System.out.println("ERRO: " + ex.getMessage().toString());
        }
    }//GEN-LAST:event_btnSalvarBairroActionPerformed

    private void btnLimparBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparBairroActionPerformed
        limparTela();
    }//GEN-LAST:event_btnLimparBairroActionPerformed

    private boolean validarDados() {
        if (txtNomeBairro.getText().trim().length() == 0) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Informe um nome corretamente", 'a');
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    private void limparTela() {
        try {
            lblId.setText("ID");
            txtNomeBairro.setText("");
            jcbCidade.setSelectedIndex(0);

            atualizarTabela();

        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
        }
    }

    private void atualizarTabela() {
        try {

            objBairroControle = new BairroController();
            objBairroControle.preencherBairro(jtbBairros);

        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("ERRO:" + ex.getMessage());
        }
    }

    private void preencherCampos(Bairro objeto) {
        try {
            lblId.setText(String.valueOf(objeto.getId()));
            txtNomeBairro.setText(objeto.getNome());
            cbCombos.SetaComboBox(String.valueOf(objeto.getId_cidade()));
            atualizarTabela();

        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadBairros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadBairros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadBairros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadBairros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadBairros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimparBairro;
    private javax.swing.JButton btnSalvarBairro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbCidade;
    private javax.swing.JTable jtbBairros;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNomeBairro;
    private javax.swing.JTextField txtNomeBairro;
    // End of variables declaration//GEN-END:variables
}
