package views;

import tools.CaixaDeDialogo;
import tools.Combos;

public class CadBairros extends javax.swing.JFrame {

    Combos cbCombos;

    public CadBairros() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblNomeBairro = new javax.swing.JLabel();
        txtNomeBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        jcbCidade = new javax.swing.JComboBox<>();
        btnSalvarBairro = new javax.swing.JButton();
        btnLimparBairro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbBairros = new javax.swing.JTable();
        lblAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro de Bairros");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 177, -1));

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblId.setText("ID");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lblNomeBairro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNomeBairro.setText("Nome *");
        getContentPane().add(lblNomeBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 66, -1, -1));
        getContentPane().add(txtNomeBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 88, 180, -1));

        lblCidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCidade.setText("Cidade *");
        getContentPane().add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 128, -1, -1));

        jcbCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 150, 81, -1));

        btnSalvarBairro.setText("SALVAR");
        getContentPane().add(btnSalvarBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 191, -1, -1));

        btnLimparBairro.setText("LIMPAR");
        getContentPane().add(btnLimparBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 191, -1, -1));

        jtbBairros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbBairros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 225, 376, 163));

        lblAviso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAviso.setText("Campos com * são obrigatórios");
        getContentPane().add(lblAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 394, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadBairros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadBairros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadBairros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadBairros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadBairros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimparBairro;
    private javax.swing.JButton btnSalvarBairro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbCidade;
    private javax.swing.JTable jtbBairros;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNomeBairro;
    private javax.swing.JTextField txtNomeBairro;
    // End of variables declaration//GEN-END:variables
}
